title:            Lancer's Blog
description:      #一个分享Web应用, 自学PHP开发的空间
disqus_shortname: Lancer He
comments:         true
share:            true
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://www.crackedzone.com
relative_permalinks: true


# Owner/author information
owner:
  name:           Lancer He (CrackedZone)
  avatar:         avatar.jpg
  bio:            "My name is Lancer He."
  email:          lancer.he@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       Lancer He
  github:         Lancer He
  stackexchange:  
  linkedin:       Lancer He
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   #https://plus.google.com/u/0/113657239096231891266

# Background image to be tiled on all pages
background: ps_neutral.png
feature: 25.jpg
qiniu: 25.jpg

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-37439194-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  #- title: BAE Blog(abandon)
  #  url: http://www.baidu.com
  # external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
pygments:    true
markdown:    kramdown

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough","superscript"]

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:year/:month/:day/:title 

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]